# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_model_dropdown(object):
    def setupUi(self, model_dropdown):
        model_dropdown.setObjectName("model_dropdown")
        model_dropdown.resize(800, 400)
        self.hyperparameters = QtWidgets.QComboBox(model_dropdown)
        self.hyperparameters.setGeometry(QtCore.QRect(20, 20, 300, 30))
        self.hyperparameters.setMinimumSize(QtCore.QSize(0, 0))
        self.hyperparameters.setObjectName("hyperparameters")
        self.models_dropdown = QtWidgets.QComboBox(model_dropdown)
        self.models_dropdown.setGeometry(QtCore.QRect(480, 20, 300, 30))
        self.models_dropdown.setObjectName("models_dropdown")
        self.activation_dropdown = QtWidgets.QComboBox(model_dropdown)
        self.activation_dropdown.setGeometry(QtCore.QRect(480, 200, 300, 30))
        self.activation_dropdown.setObjectName("activation_dropdown")
        self.parameter_slider = QtWidgets.QSlider(model_dropdown)
        self.parameter_slider.setGeometry(QtCore.QRect(20, 200, 300, 30))
        self.parameter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.parameter_slider.setObjectName("parameter_slider")
        self.hyper_edit = QtWidgets.QLineEdit(model_dropdown)
        self.hyper_edit.setGeometry(QtCore.QRect(20, 250, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.hyper_edit.setFont(font)
        self.hyper_edit.setObjectName("hyper_edit")
        self.submit_button = QtWidgets.QPushButton(model_dropdown)
        self.submit_button.setGeometry(QtCore.QRect(580, 330, 100, 50))
        self.submit_button.setObjectName("submit_button")
        self.close_button = QtWidgets.QPushButton(model_dropdown)
        self.close_button.setGeometry(QtCore.QRect(680, 330, 100, 50))
        self.close_button.setObjectName("close_button")

        self.retranslateUi(model_dropdown)
        QtCore.QMetaObject.connectSlotsByName(model_dropdown)

    def retranslateUi(self, model_dropdown):
        _translate = QtCore.QCoreApplication.translate
        model_dropdown.setWindowTitle(_translate("model_dropdown", "Form"))
        self.hyper_edit.setText(_translate("model_dropdown", "63463"))
        self.submit_button.setText(_translate("model_dropdown", "Submit"))
        self.close_button.setText(_translate("model_dropdown", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    model_dropdown = QtWidgets.QWidget()
    ui = Ui_model_dropdown()
    ui.setupUi(model_dropdown)
    model_dropdown.show()
    sys.exit(app.exec_())
