# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'title_notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        font = QtGui.QFont()
        font.setKerning(False)
        Form.setFont(font)
        self.title_edit = QtWidgets.QLineEdit(Form)
        self.title_edit.setGeometry(QtCore.QRect(20, 20, 560, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.title_edit.setFont(font)
        self.title_edit.setText("")
        self.title_edit.setObjectName("title_edit")
        self.notes_edit = QtWidgets.QLineEdit(Form)
        self.notes_edit.setGeometry(QtCore.QRect(20, 90, 560, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes_edit.sizePolicy().hasHeightForWidth())
        self.notes_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.notes_edit.setFont(font)
        self.notes_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.notes_edit.setText("")
        self.notes_edit.setObjectName("notes_edit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 180, 200, 100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 170, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #5AAAA4; border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.save_model = QtWidgets.QCheckBox(Form)
        self.save_model.setGeometry(QtCore.QRect(20, 215, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setKerning(False)
        self.save_model.setFont(font)
        self.save_model.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.save_model.setChecked(False)
        self.save_model.setTristate(False)
        self.save_model.setObjectName("save_model")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        
    def enter_into_database(self):
        return self.title_edit.text(), self.notes_edit.text()
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_edit.setPlaceholderText(_translate("Form", "Enter Title"))
        self.notes_edit.setPlaceholderText(_translate("Form", "Add Additional Notes"))
        self.pushButton.setText(_translate("Form", "RUN"))
        self.save_model.setText(_translate("Form", "Save Model"))



